
#All can connect to the DB using MySql workbench
#Use sm-portal-db.cbhkkpofzghu.us-east-1.rds.amazonaws.com as Host name 3306 as port
#Use Welcome1A as passWord and sm-portal-db as DB name
#db-name: sm-portal-db
#db-pass: Welcome1A #DxkveN5gAmlid0OeQZFu #Welcome1A


#logging.level.org.h2.server:DEBUG
#Database
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)

#spring.datasource.url = jdbc:mysql://localhost:3306/HotelSystemDB?useSSL=false
spring.datasource:
  driver: com.mysql.cj.jdbc.Driver
  url : jdbc:mysql://database-1.cbhkkpofzghu.us-east-1.rds.amazonaws.com:3306/portal?createDatabaseIfNotExist=true #jdbc:mysql://sm-portal-db.cbhkkpofzghu.us-east-1.rds.amazonaws.com:3306/portal?createDatabaseIfNotExist=true
  username : admin
  password : Welcome1A

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa:
  properties.hibernate.dialect : org.hibernate.dialect.MySQL57Dialect #MySQL8Dialect #MySQL55Dialect #MySQL5Dialect #MySQLInnoDBDialect #MySQLMyISAMDialect #MySQL5InnoDBDialect
  hibernate.ddl-auto : create-drop #update #create-drop
  
#Get Actuatr health
management:
  security.enabled : false
  endpoints:
    web:
      exposure:
        exclude: "*"
  

  